[package]
name = "TeleportationRoqoqo"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
qoqo_calculator = "1.1.2"
roqoqo = "1.6.0"
roqoqo-quest = "0.11.1"
