[package]
name = "QuantumRustProject"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
deep-clone = "0.1.0"
q1tsim = "0.5.0"
rand = "0.8.5"

